//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parcial_Uno_GPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MateriaPrima
    {
        public int idMaterial { get; set; }
        public string nombreMat { get; set; }
        public string descripcionMat { get; set; }
        public Nullable<double> stock { get; set; }
        public string medida { get; set; }
        public Nullable<double> stockMinimo { get; set; }
        public Nullable<int> estado { get; set; }
    }
}
