//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parcial_Uno_GPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public int idProd { get; set; }
        public string nombreProd { get; set; }
        public string descripcionProd { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<int> estado { get; set; }
    }
}
