//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parcial_Uno_GPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int idUser { get; set; }
        public string nameUser { get; set; }
        public string passUser { get; set; }
        public Nullable<int> rol { get; set; }
    
        public virtual Vista Vista { get; set; }
    }
}
